theme: jekyll-theme-leap-day
title: "<a href=\"www.sigdial.org/workshops/conference19/\">SIGDIAL 2018</a> Special Session"
description: "on Conversational Approaches to Information Search, </br> Retrieval, and Presentation </br> Melbourne, Australia </br> July 12-14, 2018"
