theme: jekyll-theme-leap-day
title: "<a href=\"www.sigdial.org/workshops/conference19/\">SIGDIAL 2018</a> Special Session on Conversational Approaches to Information Search, Retrieval, and Presentation"
description: "Melbourne, Australia </br> July 12-14, 2018"
