theme: jekyll-theme-massively
title: "<a href=\"www.sigdial.org/workshops/conference19/\">SIGDIAL 2018</a> Special Session on </br> Conversational Approaches to Information Search, </br> Retrieval, and Presentation"
description: "Melbourne, Australia </br> July 12-14, 2018"
